[package]
name = "sound"
version = "0.1.0"
edition = "2018"

[[example]]
name = "rodio_soundgen"
path = "examples/rodio_soundgen.rs"

[dependencies]
rodio = { version = "0.14.0", default-features = false }
stft = { version = "*", git = "https://github.com/sunsided/stft", rev = "8547443b9bb805a967e8d8c079c3cfe7be5ef04f" }

[profile.dev.package.rodio]
opt-level = 3
