[package]
name = "sound"
version = "0.1.0"
edition = "2018"

[[example]]
name = "rodio_soundgen"
path = "examples/rodio_soundgen.rs"

[dependencies]
rodio = { version = "0.14.0", default-features = false }
rustfft = "6.0.1"
num = "0.4.0"
apodize = "1.0.0"
strider = "0.1.3"

[profile.dev.package.rodio]
opt-level = 3

[dev-dependencies]
approx = { version = "0.5.0", features = ["num-complex"] }
